version: '3.9'

services:

  # ─────────────────────────────────────────
  # Contenedor 1: Base de datos MySQL
  # ─────────────────────────────────────────
  db:
    image: mysql:8.0
    container_name: crud_clientes_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} #APLICAR VARIABLE DE ENTORNO PARA MEJORAR LA SEGURIDAD
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    healthcheck:
      test: >
        mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD}
      interval: 10s
      timeout: 5s
      retries: 5

  # ─────────────────────────────────────────
  # Contenedor 2: PHP 8.2 + Apache (sin cambios)
  # ─────────────────────────────────────────
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud_clientes_app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html #CAMBIAR PARA MEJORAR LA SEGURIDAD: solo montar lo necesario, no todo el src
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  # ─────────────────────────────────────────
  # Contenedor 3: Django + DRF  ← NUEVO
  # Puerto 8000 para no chocar con PHP (8080)
  # ─────────────────────────────────────────
  django:
    build:
      context: ./django_api
      dockerfile: Dockerfile
    container_name: crud_clientes_django
    restart: unless-stopped
    ports:
      - "8000:8000"           # API disponible en http://localhost:8000
    volumes:
      - ./django_api:/app     # hot-reload: cambios en código se reflejan al instante
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DEBUG=${DEBUG}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  # ─────────────────────────────────────────
  # phpMyAdmin
  # ─────────────────────────────────────────
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: crud_clientes_pma
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
